# Naive Bayes Analysis

## Gaussian Naive Bayes

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Load the preprocessed dataset
df = pd.read_csv('../../data/final_processed_dataset_V2.csv')
df = df.dropna()

# 2. Separate features (X) and target (y)
X = df.drop(['track_popularity', 'is_hit'], axis=1) # Drop original popularity and the target itself
y = df['is_hit']

# 3. Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# 4. Initialize and train the Gaussian Naive Bayes model
model = GaussianNB()
model.fit(X_train, y_train)

# 5. Make predictions on the test set
y_pred = model.predict(X_test)

# 6. Evaluate the model
acc_gaussian = accuracy_score(y_test, y_pred)
print("Naive Bayes Model Performance:")
print(f"Accuracy: {acc_gaussian:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Naive Bayes Model Performance:
Accuracy: 0.7969

Classification Report:
              precision    recall  f1-score   support

           0       0.48      0.39      0.43       153
           1       0.86      0.90      0.88       630

    accuracy                           0.80       783
   macro avg       0.67      0.64      0.65       783
weighted avg       0.78      0.80      0.79       783


Confusion Matrix:
[[ 60  93]
 [ 66 564]]


In [15]:
import pandas as pd
from sklearn.preprocessing import KBinsDiscretizer

# 1. Load the dataset for Categorical Naive Bayes preprocessing
df_cat = pd.read_csv('../../data/final_processed_dataset_V2.csv')
df_cat = df_cat.dropna()

# 2. Identify the target variable `is_hit` and store it separately.
y_cat = df_cat['is_hit']
X_cat = df_cat.drop('is_hit', axis=1)

print("Original DataFrame head:")
print(df_cat.head())
print(f"\nShape of df_cat: {df_cat.shape}")

Original DataFrame head:
   acousticness  danceability  energy  valence    tempo  loudness  \
0      0.755000         0.753   0.922    0.870   97.360    -5.154   
1      0.792000         0.541   0.443    0.506  145.819    -7.863   
2      0.012700         0.656   0.717    0.809  123.988    -4.871   
3      0.000989         0.602   0.955    0.193  126.009    -4.888   
4      0.701000         0.495   0.498    0.320  133.992    -7.023   

   speechiness  instrumentalness  track_popularity  is_hit  
0       0.0771          0.071100              54.0       1  
1       0.0287          0.000000               0.0       0  
2       0.0279          0.000012              62.0       1  
3       0.1540          0.013300              57.0       1  
4       0.0337          0.000000              65.0       1  

Shape of df_cat: (2608, 10)


In [16]:
from sklearn.preprocessing import KBinsDiscretizer

# Define columns to discretize
columns_to_discretize = ['acousticness', 'danceability', 'energy', 'tempo']

# Initialize KBinsDiscretizer with 'quantile' strategy and 5 bins
discretizer = KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='quantile', subsample=None, random_state=42)

# Apply discretizer to the selected columns
X_discretized_array = discretizer.fit_transform(X_cat[columns_to_discretize])

# Create a DataFrame from the discretized array
X_discretized_df = pd.DataFrame(X_discretized_array, columns=[col + '_binned' for col in columns_to_discretize])

# Replace original columns with binned versions
X_cat_processed = X_cat.drop(columns=columns_to_discretize + ['valence', 'track_popularity'])
X_cat_processed = pd.concat([X_cat_processed.reset_index(drop=True), X_discretized_df], axis=1)

print("Features DataFrame head after discretization:")
print(X_cat_processed.head())
print(f"\nShape of X_cat_processed: {X_cat_processed.shape}")

Features DataFrame head after discretization:
   loudness  speechiness  instrumentalness  acousticness_binned  \
0    -5.154       0.0771          0.071100                  4.0   
1    -7.863       0.0287          0.000000                  4.0   
2    -4.871       0.0279          0.000012                  1.0   
3    -4.888       0.1540          0.013300                  0.0   
4    -7.023       0.0337          0.000000                  4.0   

   danceability_binned  energy_binned  tempo_binned  
0                  4.0            4.0           1.0  
1                  1.0            0.0           3.0  
2                  3.0            2.0           2.0  
3                  2.0            4.0           2.0  
4                  1.0            1.0           3.0  

Shape of X_cat_processed: (2608, 7)


In [17]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train_cat, X_test_cat, y_train_cat, y_test_cat = train_test_split(
    X_cat_processed, y_cat, test_size=0.3, random_state=42, stratify=y_cat
)

print(f"Shape of X_train_cat: {X_train_cat.shape}")
print(f"Shape of X_test_cat: {X_test_cat.shape}")
print(f"Shape of y_train_cat: {y_train_cat.shape}")
print(f"Shape of y_test_cat: {y_test_cat.shape}")


Shape of X_train_cat: (1825, 7)
Shape of X_test_cat: (783, 7)
Shape of y_train_cat: (1825,)
Shape of y_test_cat: (783,)


In [18]:
import pandas as pd
from sklearn.preprocessing import KBinsDiscretizer

# Reload for complete feature discretization
df_cat = pd.read_csv('../../data/final_processed_dataset_V2.csv')
df_cat = df_cat.dropna()
y_cat = df_cat['is_hit']
X_cat = df_cat.drop(['is_hit', 'track_popularity'], axis=1)

columns_to_discretize = ['acousticness', 'danceability', 'energy', 'valence',
                         'tempo', 'loudness', 'speechiness', 'instrumentalness']

print("Original DataFrame head (after dropping is_hit):")
print(X_cat.head())
print(f"\nShape of X_cat: {X_cat.shape}")

Original DataFrame head (after dropping is_hit):
   acousticness  danceability  energy  valence    tempo  loudness  \
0      0.755000         0.753   0.922    0.870   97.360    -5.154   
1      0.792000         0.541   0.443    0.506  145.819    -7.863   
2      0.012700         0.656   0.717    0.809  123.988    -4.871   
3      0.000989         0.602   0.955    0.193  126.009    -4.888   
4      0.701000         0.495   0.498    0.320  133.992    -7.023   

   speechiness  instrumentalness  
0       0.0771          0.071100  
1       0.0287          0.000000  
2       0.0279          0.000012  
3       0.1540          0.013300  
4       0.0337          0.000000  

Shape of X_cat: (2608, 8)


In [19]:
from sklearn.preprocessing import KBinsDiscretizer

# Complete discretization for Categorical NB
discretizer = KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='quantile', subsample=None, random_state=42)
X_discretized_array = discretizer.fit_transform(X_cat[columns_to_discretize])
X_cat_processed = pd.DataFrame(X_discretized_array, columns=[col + '_binned' for col in columns_to_discretize])

print("Features DataFrame head after complete discretization:")
print(X_cat_processed.head())
print(f"\nShape of X_cat_processed: {X_cat_processed.shape}")

Features DataFrame head after complete discretization:
   acousticness_binned  danceability_binned  energy_binned  valence_binned  \
0                  4.0                  4.0            4.0             4.0   
1                  4.0                  1.0            0.0             2.0   
2                  1.0                  3.0            2.0             4.0   
3                  0.0                  2.0            4.0             0.0   
4                  4.0                  1.0            1.0             1.0   

   tempo_binned  loudness_binned  speechiness_binned  instrumentalness_binned  
0           1.0              3.0                 3.0                      2.0  
1           3.0              1.0                 0.0                      0.0  
2           2.0              3.0                 0.0                      0.0  
3           2.0              3.0                 4.0                      2.0  
4           3.0              1.0                 1.0                      0.

In [20]:
from sklearn.model_selection import train_test_split

# Re-split after complete discretization
X_train_cat, X_test_cat, y_train_cat, y_test_cat = train_test_split(
    X_cat_processed, y_cat, test_size=0.3, random_state=42, stratify=y_cat
)

print(f"Shape of X_train_cat: {X_train_cat.shape}")
print(f"Shape of X_test_cat: {X_test_cat.shape}")
print(f"Shape of y_train_cat: {y_train_cat.shape}")
print(f"Shape of y_test_cat: {y_test_cat.shape}")

Shape of X_train_cat: (1825, 8)
Shape of X_test_cat: (783, 8)
Shape of y_train_cat: (1825,)
Shape of y_test_cat: (783,)


## Categorical Naive Bayes

In [21]:
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize and train the Categorical Naive Bayes model
model_cat = CategoricalNB()
model_cat.fit(X_train_cat, y_train_cat)

# Make predictions on the test set
y_pred_cat = model_cat.predict(X_test_cat)

# Evaluate the model
acc_categorical = accuracy_score(y_test_cat, y_pred_cat)
print("Categorical Naive Bayes Model Performance:")
print(f"Accuracy: {acc_categorical:.4f}")
print("\nClassification Report:")
print(classification_report(y_test_cat, y_pred_cat))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_cat, y_pred_cat))

Categorical Naive Bayes Model Performance:
Accuracy: 0.7854

Classification Report:
              precision    recall  f1-score   support

           0       0.45      0.42      0.43       153
           1       0.86      0.87      0.87       630

    accuracy                           0.79       783
   macro avg       0.65      0.65      0.65       783
weighted avg       0.78      0.79      0.78       783


Confusion Matrix:
[[ 64  89]
 [ 79 551]]


## Comparison of Naive Bayes Models

In [22]:
import pandas as pd

# Store the accuracy scores in a DataFrame
model_accuracies = {
    'Model': ['Gaussian Naive Bayes', 'Categorical Naive Bayes'],
    'Accuracy': [acc_gaussian, acc_categorical]
}

df_accuracies = pd.DataFrame(model_accuracies)

print("Model Accuracies:")
print(df_accuracies)

Model Accuracies:
                     Model  Accuracy
0     Gaussian Naive Bayes    0.7969
1  Categorical Naive Bayes    0.7854


In [24]:
import matplotlib.pyplot as plt
import seaborn as sns

# Create a bar chart using the collected accuracy scores
plt.figure(figsize=(8, 5))
sns.barplot(x='Model', y='Accuracy', data=df_accuracies, palette='viridis', hue='Model', legend=False)

plt.title('Comparison of Naive Bayes Model Accuracies')
plt.xlabel('Model')
plt.ylabel('Accuracy')

# Display accuracy values on top of each bar
for index, row in df_accuracies.iterrows():
    plt.text(index, row['Accuracy'] + 0.005, f"{row['Accuracy']:.4f}", color='black', ha="center")

plt.ylim(0.5, 1.0)
plt.show()

## Summary

### Data Analysis Key Findings

*   The **Gaussian Naive Bayes** model achieved an accuracy of **0.7969**, outperforming the **Categorical Naive Bayes** model, which scored **0.7854**.
*   Discretizing all continuous features allowed for the use of Categorical Naive Bayes, but it did not lead to a performance improvement over the Gaussian approach in this instance. This suggests that the continuous distributions were already reasonably well-modeled by the Gaussian assumption or that the binning process simplified the data too much.
*   Both models provide a strong baseline for classification on this dataset.

### Insights and Next Steps

*   Gaussian Naive Bayes is currently the preferred model for this feature set due to higher accuracy.
*   Further tuning of the discretization strategy (e.g., number of bins, strategy='uniform') could be explored to see if Categorical NB can be improved.

### Confusion Matrix Visualization

In [25]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.metrics import confusion_matrix

cm_gaussian = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(cm_gaussian, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix: Gaussian Naive Bayes')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

In [26]:
cm_categorical = confusion_matrix(y_test_cat, y_pred_cat)

plt.figure(figsize=(6, 5))
sns.heatmap(cm_categorical, annot=True, fmt='d', cmap='Greens', cbar=False,
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix: Categorical Naive Bayes')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

## Hyperparameter Tuning: Optimizing Bin Sizes (Brackets) for Categorical NB

We will now test different bin sizes (from 2 to 20) for the discretization process to find the optimal configuration for our Categorical Naive Bayes model. This hyperparameter tuning aims to see if a finer or coarser discretization can lead to better predictive performance.

In [ ]:
import matplotlib.pyplot as plt
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import accuracy_score

bin_range = range(2, 21)
accuracies = []

for bins in bin_range:
    # Discretize X_cat[columns_to_discretize] using the current bin size
    discretizer = KBinsDiscretizer(n_bins=bins, encode='ordinal', strategy='quantile', subsample=None, random_state=42)
    X_discretized = discretizer.fit_transform(X_cat[columns_to_discretize])
    X_discretized_df = pd.DataFrame(X_discretized, columns=[col + '_binned' for col in columns_to_discretize])
    
    # Splitting the data
    X_train_bin, X_test_bin, y_train_bin, y_test_bin = train_test_split(
        X_discretized_df, y_cat, test_size=0.3, random_state=42, stratify=y_cat
    )
    
    # Trains a CategoricalNB model
    model_bin = CategoricalNB()
    model_bin.fit(X_train_bin, y_train_bin)
    
    # Calculates and stores the accuracy
    y_pred_bin = model_bin.predict(X_test_bin)
    acc = accuracy_score(y_test_bin, y_pred_bin)
    accuracies.append(acc)

# Plots the accuracies
plt.figure(figsize=(10, 6))
plt.plot(bin_range, accuracies, marker='o', label='Categorical NB Accuracy')
plt.axhline(y=acc_gaussian, color='r', linestyle='--', label='Gaussian NB Baseline')
plt.title('Categorical NB Accuracy vs. Number of Bins')
plt.xlabel('Number of Bins')
plt.ylabel('Accuracy')
plt.xticks(bin_range)
plt.legend()
plt.grid(True)
plt.show()

# Prints the best accuracy and corresponding bin size
best_acc = max(accuracies)
best_bins = bin_range[accuracies.index(best_acc)]
print(f"Best Accuracy: {best_acc:.4f} with {best_bins} bins")

### Final Benchmark Observation

The line chart above illustrates how the accuracy of the Categorical Naive Bayes model varies with different bin sizes. If Categorical NB outperforms Gaussian NB at any point, the blue line will be above the red dashed baseline.

## Final Performance Comparison

We are now comparing the original models with the optimized version.

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Create a DataFrame with the three model results
comparison_data = {
    'Model': ['Gaussian NB', 'Categorical NB (5 Bins)', 'Optimized Categorical NB'],
    'Accuracy': [acc_gaussian, acc_categorical, best_acc]
}
df_comparison = pd.DataFrame(comparison_data)

# 2. Plot the bar chart using Seaborn
plt.figure(figsize=(10, 6))
ax = sns.barplot(x='Model', y='Accuracy', data=df_comparison, palette='magma', hue='Model', legend=False)

# 3. Annotate the bars with accuracy values
for p in ax.patches:
    ax.annotate(f'{p.get_height():.4f}', 
                (p.get_x() + p.get_width() / 2., p.get_height()), 
                ha='center', va='center', 
                xytext=(0, 9), 
                textcoords='offset points')

# 4. Final touches
plt.title('Final Comparison: Naive Bayes Variants')
plt.ylim(0.7, 0.85)
plt.ylabel('Accuracy')
plt.show()